export const colors = [
    { name: "Amarelo",  value: "yellow",   hex: "#eab308" },
    { name: "Azul",     value: "blue",     hex: "#3b82f6" },
    { name: "Ciano",    value: "cyan",     hex: "#06b6d4" },
    { name: "Cinza",    value: "gray",     hex: "#6b7280" },
    { name: "Laranja",  value: "orange",   hex: "#f97316" },
    { name: "Lima",     value: "lime",     hex: "#84cc16" },
    { name: "Magenta",  value: "fuchsia",  hex: "#d946ef" },
    { name: "Marrom",   value: "brown",    hex: "#92400e" },
    { name: "Prata",    value: "silver",   hex: "#a1a1aa" },
    { name: "Preto",    value: "black",    hex: "#000000" },
    { name: "Rosa",     value: "pink",     hex: "#ec4899" },
    { name: "Roxo",     value: "purple",   hex: "#a855f7" },
    { name: "Turquesa", value: "teal",     hex: "#14b8a6" },
    { name: "Verde",    value: "green",    hex: "#22c55e" },
    { name: "Vermelho", value: "red",      hex: "#ef4444" },
];
